name: Update Ranking

on:
  issues:
    types: [opened]

jobs:
  update-ranking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update ranking
        env:
          GITHUB_TOKEN: ${{ secrets.BABA_GITHUB_TOKEN }}
        run: |
          # Parse issue title for name and score
          ISSUE_TITLE="${{ github.event.issue.title }}"
          NAME=$(echo $ISSUE_TITLE | cut -d '|' -f 1)
          SCORE=$(echo $ISSUE_TITLE | cut -d '|' -f 2)
          
          # Update ranking.json
          jq --arg name "$NAME" --arg score "$SCORE" --arg date "$(date -Iseconds)" \
            '. += [{"name": $name, "score": $score|tonumber, "date": $date}] | sort_by(.score) | .[0:10]' \
            ranking.json > tmp.json && mv tmp.json ranking.json
          
          # Commit and push changes
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ranking.json
          git commit -m "Update ranking"
          git push
